name: github-training-2
on: 
  push:
    branches: 
      - main
    paths-ignore:    
       .github/**
  pull_request:
    branches:      main
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
jobs:
  job1:
    name: my first step
    runs-on: ubuntu-latest
    steps:
      - run: 
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
          
      
 
  
        
       
   
